export { makeRng, hashSeed, type Rng } from "./rng.js";
export {
  ELEMENTS,
  ELEMENT_PALETTES,
  FEELS,
  PALETTE_SLOTS,
  elementSchema,
  feelSchema,
  paletteFor,
  resolveColor,
  type Element,
  type ElementPalette,
  type Feel,
  type Palette,
  type PaletteSlot,
} from "./elements.js";
export {
  ANCHORS,
  PHASES,
  VFX_MODULE_KINDS,
  VFX_MODULE_SCHEMAS,
  anchorSchema,
  beamModuleSchema,
  boltModuleSchema,
  columnModuleSchema,
  completeModule,
  curveSchema,
  lightModuleSchema,
  meshModuleSchema,
  parseVfxEffect,
  particlesModuleSchema,
  phaseSchema,
  ringModuleSchema,
  shakeModuleSchema,
  shellModuleSchema,
  slashModuleSchema,
  soundModuleSchema,
  spriteModuleSchema,
  telegraphModuleSchema,
  trailModuleSchema,
  unitCurveSchema,
  vfxEffectSchema,
  vfxModuleSchema,
  type Anchor,
  type AnchorAt,
  type Curve,
  type Phase,
  type VfxEffect,
  type VfxModule,
  type VfxModuleKind,
  type VfxModuleOf,
} from "./modules.js";
export {
  SPELL_KINDS,
  SPELL_KIND_NOTES,
  STATUS_EFFECTS,
  statusEffectSchema,
  type StatusEffect,
  isSustainedKind,
  isTelegraphedKind,
  parseSpell,
  phaseEffect,
  phasesForKind,
  spellArchetypeSchema,
  spellKindSchema,
  spellPalette,
  spellSchema,
  spellTimeline,
  type SpellArchetype,
  type SpellDoc,
  type SpellKind,
  type SpellTimeline,
} from "./spell.js";
export { PRESETS, presetById, presetsFor } from "./library.js";
export {
  GRAMMAR,
  BASE_PRESETS,
  SLOTS,
  SPRITE_ROLES,
  SYMBOL_ORIENTS,
  SYMBOL_ROLES,
  SYMBOL_SPINS,
  symbolSpin,
  symbolSprite,
  symbolsFor,
  type MaskEntry,
  type Preset,
  type PresetContext,
  type Slot,
  type SlotRule,
  type SpriteCatalog,
  type SpriteEntry,
  type SpriteRole,
  type SymbolCatalogDoc,
  type SymbolEntry,
  type SymbolOrient,
  type SymbolRole,
  type SymbolSpin,
} from "./presets.js";
export { expandRepeat, repeatCopy, repeatCount } from "./repeat.js";
export {
  DODGE_REACTION,
  DODGE_SPEED,
  addFromPreset,
  buildFromPreset,
  generatePhase,
  generatePhases,
  generateSpell,
  phaseAnchor,
  presetsAvailable,
  randomArchetype,
  rerollModule,
  type GenerateOptions,
} from "./generator.js";
export {
  BUDGET,
  auditSpell,
  effectStats,
  moduleDuration,
  moduleParticles,
  spellStats,
  type PhaseStats,
  type SpellStats,
  type SpellViolation,
} from "./audit.js";
