import { z } from "zod";

/**
 * What a town's people know about where things are — generated from the
 * world, never written by hand.
 *
 * RULE: quest and NPC text never carries a literal compass word. It names a
 * place (`{dir:cove}`, `{far:cove}`, `{place:cove}`) and the direction and
 * distance are computed here, from the world the text is running in. Every
 * server generates its own world, so a hand-written "the northern cove" is a
 * guess that goes stale on the next world — and the first town shipped with
 * every north/south flipped. North is -Z (the HUD compass, core `bearing`).
 */
export const placesSchema = z
  .object({
    origin: z.tuple([z.number(), z.number()]).describe("[x, z] the directions are measured FROM — the town's centre."),
    places: z
      .record(
        z.string(),
        z.object({
          at: z.tuple([z.number(), z.number()]).describe("[x, z] world position."),
          name: z.string().default("").describe("What people call it (\"the Drowned Lantern\", \"Ashfall\"); empty = unnamed."),
          kind: z.string().default("").describe("resident | gate | poi | camp | town | capital | point — what generated it."),
        }),
      )
      .default({}),
  })
  .describe(
    "A town's geography (assets/places/<town>.json), generated by tools/town-npcs.mts from the world: its residents, gates, " +
      "named places and camps, nearby towns and every continent's capital. Dialogue and quest text refer to these as " +
      "{dir:id} (north-west), {Dir:id} (North-west), {far:id} (a short walk), {place:id} / {Place:id} (its name).",
  );
export type Places = z.infer<typeof placesSchema>;

const COMPASS = ["north", "north-east", "east", "south-east", "south", "south-west", "west", "north-west"] as const;

/** The 8-way compass word from one [x, z] to another (north is -Z). */
export function compassWord(from: readonly [number, number], to: readonly [number, number]): string {
  const deg = ((Math.atan2(to[0] - from[0], -(to[1] - from[1])) * 180) / Math.PI + 360) % 360;
  return COMPASS[Math.round(deg / 45) % 8]!;
}

/** Distance the way a townsperson says it. */
export function distanceWord(metres: number): string {
  if (metres < 120) return "a stone's throw";
  if (metres < 450) return "a short walk";
  if (metres < 1500) return "a good walk";
  if (metres < 4000) return "half a day on foot";
  if (metres < 9000) return "a long day's travel";
  return "many days away, across the sea";
}

const TOKEN = /\{(dir|Dir|far|place|Place):([a-z0-9][a-z0-9_-]*)\}/g;
const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

/** Place ids a text refers to (for lint). */
export function placeTokens(text: string): string[] {
  return [...text.matchAll(TOKEN)].map((m) => m[2]!);
}

/**
 * Fill {dir:id} {Dir:id} {far:id} {place:id} {Place:id} from the places table,
 * measured from `from` (default: the table's origin). An unknown id is left as
 * "somewhere" rather than a wrong answer.
 */
export function fillPlaces(text: string, places: Places | null | undefined, from?: readonly [number, number]): string {
  if (!text.includes("{")) return text;
  return text.replace(TOKEN, (_all, kind: string, id: string) => {
    const p = places?.places[id];
    if (!p || !places) return "somewhere";
    const origin = from ?? places.origin;
    switch (kind) {
      case "dir":
        return compassWord(origin, p.at);
      case "Dir":
        return cap(compassWord(origin, p.at));
      case "far":
        return distanceWord(Math.hypot(p.at[0] - origin[0], p.at[1] - origin[1]));
      case "place":
        return p.name || id;
      default:
        return cap(p.name || id);
    }
  });
}

/** Literal compass words in a text (what the lint refuses). */
export function literalCompassWords(text: string): string[] {
  const stripped = text.replace(TOKEN, "");
  return [...stripped.matchAll(/\b(north|south|east|west)(?:ern|ward|wards)?\b/gi)].map((m) => m[0]);
}
