// Sound bridge: ElevenLabs sound effects + music, generated from a project's sound TEMPLATE and CATALOG.
//
// The template (authoring/audio/template.json) is the house style — one short global style line, a list of
// things to avoid, and per-category rules: the style words appended to every prompt of that category, the
// loudness target, loop/one-shot handling, mono/stereo, default length. The catalog
// (authoring/audio/catalog/*.json) lists the sounds themselves: an asset id, a prompt describing ONLY that
// sound, a variant count. Changing the template or a prompt makes the affected files STALE, so a restyle is
// one edit + one `gen`.
//
//   node tools/sfx-request.mjs status  --project foundation [--category melee] [--next]
//   node tools/sfx-request.mjs gen     --project foundation [--category melee] [--only 'combat/melee/sword*']
//                                      [--force] [--dry] [--concurrency 3] [--stale]
//   node tools/sfx-request.mjs one     --project foundation --id ui/click --prompt "…" --category ui [--variants 2]
//   node tools/sfx-request.mjs refit   --project foundation [--category ambience] [--only …]   # re-level installed files, no API
//   node tools/sfx-request.mjs board   --project foundation            # audition page: authoring/audio/board.html
//   node tools/sfx-request.mjs reject  --project foundation --file combat/melee/sword-swing-2.ogg [--note "…"]
//
// Output: assets/audio/<id>.<ext>; variants 2..n are <id>-2.<ext> …, so a script's comma list names them all.
// Ext: the entry's `ext`, else the category's, else "ogg" for loops/music and "mp3" for one-shots.
// Every installed file is recorded in authoring/audio/generated.json (prompt hash, loudness, peak, length);
// `status` compares that record against the catalog: ok / STALE (prompt or template changed) / MISSING /
// REJECTED (marked on the board or by `reject`, regenerated by the next gen).
//
// Post-processing (ffmpeg): one-shots are trimmed of leading/trailing silence and get a short fade-out;
// loops are left sample-exact. Everything is gain-matched to the category's LUFS target with a -1 dBTP
// ceiling (no limiter, so loop seams survive). The API key is ELEVENLABS_API_KEY from the repo-root .env.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(appRoot, "..", "..");
const [cmd, ...rest] = process.argv.slice(2);
const opt = (k, d) => { const i = rest.indexOf(`--${k}`); return i >= 0 ? rest[i + 1] : d; };
const flag = (k) => rest.includes(`--${k}`);
const usage = () => { console.error("usage: sfx-request.mjs status|gen|one|board|reject --project <name> …"); process.exit(2); };
if (!cmd) usage();

const project = opt("project");
if (!project) usage();
const projDir = path.join(appRoot, "projects", project);
const audioAuth = path.join(projDir, "authoring", "audio");
const assetsAudio = path.join(projDir, "assets", "audio");
const templateFile = path.join(audioAuth, "template.json");
const catalogDir = path.join(audioAuth, "catalog");
const recordFile = path.join(audioAuth, "generated.json");
const stageDir = path.join(appRoot, ".hitreg", "sfx-staging");
const MAX_SFX_PROMPT = 450;

function readJson(f, d) {
  if (d !== undefined && !fs.existsSync(f)) return d;
  // a reader can catch the record mid-replace on Windows: retry before believing it is broken
  for (let i = 0; ; i++) {
    try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch (e) {
      if (i < 20) { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 25); continue; }
      if (d !== undefined && e.code === "ENOENT") return d;
      throw new Error(`${f}: ${e.message}`);
    }
  }
}
function apiKey() {
  if (process.env.ELEVENLABS_API_KEY) return process.env.ELEVENLABS_API_KEY;
  const env = fs.existsSync(path.join(repoRoot, ".env")) ? fs.readFileSync(path.join(repoRoot, ".env"), "utf8") : "";
  const m = env.match(/^ELEVENLABS_API_KEY\s*=\s*(.+)$/m);
  if (!m) throw new Error("ELEVENLABS_API_KEY missing (repo-root .env)");
  return m[1].trim().replace(/^["']|["']$/g, "");
}

const template = () => readJson(templateFile);
function catalogs(category) {
  if (!fs.existsSync(catalogDir)) return [];
  return fs.readdirSync(catalogDir).filter((f) => f.endsWith(".json")).sort().map((f) => {
    const doc = readJson(path.join(catalogDir, f));
    return { file: f, ...doc };
  }).filter((c) => !category || c.category === category || c.file === `${category}.json`);
}

/** Every generated file a catalog entry expands to, with its fully composed request. */
function expand(tpl, cat, entry) {
  const catName = entry.category ?? cat.category;
  const rules = tpl.categories?.[catName];
  if (!rules) throw new Error(`${cat.file}: ${entry.id}: category "${catName}" has no rules in template.json`);
  const kind = entry.kind ?? rules.kind ?? "sfx";
  const loop = entry.loop ?? rules.loop ?? false;
  const ext = entry.ext ?? rules.ext ?? (loop || kind === "music" ? "ogg" : "mp3");
  const variants = Math.max(1, entry.variants ?? rules.variants ?? 1);
  const parts = [entry.prompt.trim().replace(/\.$/, "")];
  if (entry.style !== false) {
    if (rules.style) parts.push(rules.style);
    // a category can opt out of the global line (a tavern band is not an orchestra)
    if (rules.globalStyle !== false) {
      if (tpl.style && kind === "sfx") parts.push(tpl.style);
      if (kind === "music" && tpl.musicStyle) parts.push(tpl.musicStyle);
    }
  }
  const avoid = [...(kind === "music" ? tpl.musicAvoid ?? [] : tpl.avoid ?? []), ...(rules.avoid ?? []), ...(entry.avoid ?? [])];
  let text = parts.join(". ") + ".";
  if (avoid.length) text += ` No ${avoid.join(", no ")}.`;
  if (kind === "sfx" && text.length > MAX_SFX_PROMPT) {
    // drop the avoid list first, then the global style, before refusing
    const trimmed = parts.join(". ") + ".";
    const bare = [parts[0], rules.style].filter(Boolean).join(". ") + ".";
    text = trimmed.length <= MAX_SFX_PROMPT ? trimmed : bare;
    if (text.length > MAX_SFX_PROMPT) throw new Error(`${entry.id}: prompt is ${text.length} chars with its category style; the API takes ${MAX_SFX_PROMPT}. Shorten it.`);
  }
  const request = kind === "music"
    ? { kind, prompt: text, music_length_ms: Math.round((entry.duration ?? rules.duration ?? 120) * 1000), force_instrumental: entry.instrumental ?? rules.instrumental ?? true }
    : { kind, text, duration_seconds: entry.duration ?? rules.duration ?? null, loop, prompt_influence: entry.influence ?? rules.influence ?? 0.4, model_id: "eleven_text_to_sound_v2" };
  const post = {
    loop, lufs: entry.lufs ?? rules.lufs ?? -18, mono: entry.mono ?? rules.mono ?? false,
    trim: !loop && kind === "sfx" && (entry.trim ?? rules.trim ?? true), fadeOut: loop ? 0 : (entry.fadeOut ?? rules.fadeOut ?? 0.04),
  };
  // Level guards, applied by gen AND by `refit` to files already installed — so they stay out of the hash
  // (changing one re-processes files, it does not re-buy them):
  //  highpass    Hz: cut the sub-bass mud a generated bed can be built on
  //  rmsHeadroom dB: the unweighted mean may come no closer than this to the LUFS target. LUFS is K-weighted and
  //              nearly deaf below 100 Hz, so a bed that is mostly rumble gets gained up ~15 dB into a hum.
  const guards = { highpass: entry.highpass ?? rules.highpass ?? 0, rmsHeadroom: entry.rmsHeadroom ?? rules.rmsHeadroom ?? null };
  const out = [];
  for (let v = 1; v <= variants; v++) {
    const file = `${entry.id}${v === 1 ? "" : `-${v}`}.${ext}`;
    const hash = crypto.createHash("sha1").update(JSON.stringify({ request, post, v })).digest("hex").slice(0, 12);
    out.push({ file, id: entry.id, variant: v, category: catName, request, post: { ...post, ...guards }, hash, tags: entry.tags ?? [] });
  }
  return out;
}

function allJobs(category) {
  const tpl = template();
  const jobs = [];
  const seen = new Map();
  for (const cat of catalogs(category)) {
    for (const entry of cat.sounds ?? []) {
      if (!entry.id || !entry.prompt) throw new Error(`${cat.file}: every sound needs id + prompt`);
      if (!/^[a-z0-9][a-z0-9/-]*$/.test(entry.id)) throw new Error(`${cat.file}: bad id "${entry.id}" (lowercase path, no extension)`);
      for (const job of expand(tpl, cat, entry)) {
        if (seen.has(job.file)) throw new Error(`${job.file} listed twice (${seen.get(job.file)} and ${cat.file})`);
        seen.set(job.file, cat.file);
        jobs.push({ ...job, catalog: cat.file });
      }
    }
  }
  return jobs;
}

function stateOf(job, record) {
  const r = record[job.file];
  if (!fs.existsSync(path.join(assetsAudio, job.file))) return "MISSING";
  if (!r) return "STALE";
  if (r.rejected) return "REJECTED";
  return r.hash === job.hash ? "ok" : "STALE";
}

function globMatch(pattern, s) {
  const re = new RegExp("^" + pattern.split("*").map((p) => p.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join(".*") + "$");
  return re.test(s);
}

// ---------------------------------------------------------------------------------------------- ffmpeg
function ff(args) {
  const r = spawnSync("ffmpeg", ["-hide_banner", "-nostdin", "-y", ...args], { encoding: "utf8", maxBuffer: 64 << 20 });
  if (r.status !== 0) throw new Error(`ffmpeg failed: ${(r.stderr || "").split("\n").slice(-6).join("\n")}`);
  return r.stderr || "";
}
function measure(f) {
  const log = ff(["-i", f, "-af", "ebur128=peak=true", "-f", "null", "-"]);
  const summary = log.slice(log.lastIndexOf("Summary:"));
  const I = Number((summary.match(/I:\s+(-?[\d.]+|-inf) LUFS/) || [])[1]);
  const peak = Number((summary.match(/Peak:\s+(-?[\d.]+|-inf) dBFS/) || [])[1]);
  const dur = Number((log.match(/time=(\d+):(\d+):([\d.]+)/g) || []).pop()?.replace(/time=(\d+):(\d+):([\d.]+)/, (_, h, m, s) => String(+h * 3600 + +m * 60 + +s)));
  return { I: Number.isFinite(I) ? I : -70, peak: Number.isFinite(peak) ? peak : -70, dur };
}
/** Unweighted mean level, and how much of it sits below 150 Hz (0 dB = all of it: a rumble/hum). */
function spectrum(f) {
  const mean = (af) => Number((ff(["-i", f, "-af", af, "-f", "null", "-"]).match(/mean_volume:\s+(-?[\d.]+) dB/) || [])[1] ?? -91);
  const all = mean("volumedetect");
  const low = mean("lowpass=f=150,lowpass=f=150,volumedetect");
  return { mean: all, lowShare: low - all };
}

function postProcess(raw, dest, post) {
  const ext = path.extname(dest).slice(1);
  const pre = [];
  if (post.trim) {
    pre.push("silenceremove=start_periods=1:start_threshold=-55dB:start_silence=0.005");
    pre.push("areverse", "silenceremove=start_periods=1:start_threshold=-60dB:start_silence=0.02", "areverse");
  }
  if (post.mono) pre.push("pan=mono|c0=0.5*c0+0.5*c1");
  if (post.highpass > 0) pre.push(`highpass=f=${post.highpass}:poles=2`);
  const mid = raw.replace(/\.[^.]+$/, ".mid.wav");
  ff(["-i", raw, ...(pre.length ? ["-af", pre.join(",")] : []), "-ar", "44100", mid]);
  const m = measure(mid);
  // short hits have no gated loudness: fall back to a peak target 1 dB under the ceiling
  let gain = m.I > -69 && m.dur > 0.4 ? post.lufs - m.I : -1 - m.peak - 3;
  gain = Math.min(gain, -1 - m.peak);
  let s0 = null;
  if (post.rmsHeadroom != null) {
    s0 = spectrum(mid);
    gain = Math.min(gain, post.lufs - post.rmsHeadroom - s0.mean);
  }
  const af = [`volume=${gain.toFixed(2)}dB`];
  if (post.fadeOut > 0 && m.dur > post.fadeOut * 3) af.push(`afade=t=out:st=${Math.max(0, m.dur - post.fadeOut).toFixed(3)}:d=${post.fadeOut}`);
  if (post.trim) af.unshift("afade=t=in:d=0.003");
  const codec = ext === "ogg" ? ["-c:a", "libvorbis", "-q:a", "6"] : ext === "wav" ? [] : ["-c:a", "libmp3lame", "-b:a", "192k"];
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const tmp = dest + ".tmp." + ext;
  ff(["-i", mid, "-af", af.join(","), ...codec, tmp]);
  fs.renameSync(tmp, dest);
  fs.rmSync(mid, { force: true });
  const fin = measure(dest);
  const sp = spectrum(dest);
  return { lufs: +fin.I.toFixed(1), peak: +fin.peak.toFixed(1), seconds: +fin.dur.toFixed(2), gain: +gain.toFixed(1), mean: +sp.mean.toFixed(1), lowShare: +sp.lowShare.toFixed(1) };
}

/** Read-modify-write generated.json under a mkdir lock (atomic on every filesystem), then rename into place. */
function updateRecord(mutate) {
  const lock = recordFile + ".lock";
  for (let i = 0; ; i++) {
    try { fs.mkdirSync(lock); break; } catch {
      // a lock older than 30 s belongs to a crashed process
      try { if (Date.now() - fs.statSync(lock).mtimeMs > 30000) fs.rmSync(lock, { recursive: true, force: true }); } catch { /* gone */ }
      if (i > 2000) throw new Error(`could not lock ${recordFile}`);
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
    }
  }
  try {
    const record = readJson(recordFile, {});
    mutate(record);
    const tmp = `${recordFile}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, JSON.stringify(Object.fromEntries(Object.entries(record).sort()), null, 1) + "\n");
    // Windows refuses a rename onto a file another process has open for reading: retry briefly
    for (let i = 0; ; i++) {
      try { fs.renameSync(tmp, recordFile); break; } catch (e) {
        if (i > 50) throw e;
        Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 20);
      }
    }
  } finally { fs.rmSync(lock, { recursive: true, force: true }); }
}

// ---------------------------------------------------------------------------------------------- API
async function call(job, key) {
  const isMusic = job.request.kind === "music";
  const url = isMusic
    ? "https://api.elevenlabs.io/v1/music?output_format=mp3_44100_192"
    : "https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_192";
  const { kind, ...body } = job.request;
  if (body.duration_seconds == null) delete body.duration_seconds;
  if (!isMusic && !body.loop) delete body.loop;
  if (isMusic) body.model_id = "music_v1";
  for (let attempt = 1; ; attempt++) {
    const res = await fetch(url, { method: "POST", headers: { "xi-api-key": key, "Content-Type": "application/json" }, body: JSON.stringify(body) });
    if (res.ok) return Buffer.from(await res.arrayBuffer());
    const text = await res.text();
    const retry = res.status === 429 || res.status >= 500;
    // the account runs at most a few requests at once (shared by every gen running): wait it out
    if (retry && attempt < 12) { await new Promise((r) => setTimeout(r, Math.min(30000, 1500 * 2 ** attempt) + Math.random() * 1500)); continue; }
    let detail = text;
    try { const j = JSON.parse(text).detail; detail = j?.message ?? JSON.stringify(j); } catch { /* raw */ }
    const err = new Error(`HTTP ${res.status}: ${detail}`);
    err.fatal = res.status === 401 || /quota|credits/i.test(detail);
    throw err;
  }
}

async function runJobs(jobs, { concurrency, dry }) {
  const record = readJson(recordFile, {});
  if (dry) {
    for (const j of jobs) console.log(`${j.file}  [${j.request.kind} ${j.request.duration_seconds ?? (j.request.music_length_ms ?? 0) / 1000 ?? "auto"}s${j.post.loop ? " loop" : ""}]\n  ${j.request.text ?? j.request.prompt}`);
    const secs = jobs.reduce((a, j) => a + (j.request.duration_seconds ?? (j.request.music_length_ms ?? 0) / 1000 ?? 5), 0);
    console.log(`\n${jobs.length} files, ~${Math.round(secs)} s of audio`);
    return 0;
  }
  const key = apiKey();
  fs.mkdirSync(stageDir, { recursive: true });
  let next = 0, failed = 0, done = 0, fatal = null;
  // several gens (one per agent/category) run at once: merge one entry into the file on disk under a lock,
  // never write back a copy read minutes ago
  const save = (file, entry) => updateRecord((r) => { r[file] = entry; });
  const worker = async () => {
    while (next < jobs.length && !fatal) {
      const job = jobs[next++];
      const raw = path.join(stageDir, `${job.file.replace(/[/.]/g, "_")}.${process.pid}.mp3`);
      try {
        fs.writeFileSync(raw, await call(job, key));
        const stats = postProcess(raw, path.join(assetsAudio, job.file), job.post);
        save(job.file, { hash: job.hash, id: job.id, category: job.category, prompt: job.request.text ?? job.request.prompt, at: new Date().toISOString(), ...stats });
        done++;
        const hum = job.post.loop && stats.lowShare > -3 ? "  HUM? mostly <150 Hz — listen, or reword (no hum/drone/rumble)" : "";
        console.log(`ok   ${job.file}  ${stats.seconds}s ${stats.lufs} LUFS pk ${stats.peak} mean ${stats.mean}${hum}`);
      } catch (e) {
        failed++;
        console.log(`FAIL ${job.file}  ${e.message}`);
        if (e.fatal) fatal = e;
      } finally { fs.rmSync(raw, { force: true }); }
    }
  };
  await Promise.all(Array.from({ length: Math.max(1, concurrency) }, worker));
  console.log(`\n${done} generated, ${failed} failed${fatal ? ` — stopped: ${fatal.message}` : ""}`);
  return failed ? 1 : 0;
}

// ---------------------------------------------------------------------------------------------- board
function board() {
  const jobs = allJobs(opt("category"));
  const record = readJson(recordFile, {});
  const byCat = new Map();
  for (const j of jobs) { if (!byCat.has(j.category)) byCat.set(j.category, []); byCat.get(j.category).push(j); }
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
  let rows = "";
  for (const [cat, list] of byCat) {
    rows += `<h2>${esc(cat)} <small>${list.length}</small></h2>`;
    for (const j of list) {
      const r = record[j.file] ?? {};
      const st = stateOf(j, record);
      rows += `<div class="row ${st}" data-file="${esc(j.file)}"><label><input type="checkbox" class="rej"> reject</label>
<div class="meta"><b>${esc(j.file)}</b> <span class="st">${st}</span> <span>${r.seconds ?? "?"}s · ${r.lufs ?? "?"} LUFS${j.post.loop ? " · loop" : ""}</span><br><em>${esc(r.prompt ?? j.request.text ?? j.request.prompt)}</em></div>
${st === "MISSING" ? "" : `<audio controls preload="none" ${j.post.loop ? "loop" : ""} src="../../assets/audio/${esc(j.file)}"></audio>`}<input class="note" placeholder="what's wrong"></div>`;
    }
  }
  const html = `<!doctype html><meta charset="utf-8"><title>Sound board — ${esc(project)}</title>
<style>body{font:13px system-ui;background:#111;color:#ddd;margin:16px}h2{margin:24px 0 6px;color:#fff}small{color:#888}
.row{display:grid;grid-template-columns:70px 1fr 300px 200px;gap:10px;align-items:center;padding:6px;border-bottom:1px solid #222}
.row em{color:#999}.st{font-weight:600}.MISSING .st{color:#e66}.STALE .st{color:#eb4}.REJECTED .st{color:#e6e}.ok .st{color:#6c6}
audio{width:300px;height:32px}input.note{background:#222;color:#ddd;border:1px solid #333;padding:4px}
#bar{position:sticky;top:0;background:#111;padding:8px 0;border-bottom:1px solid #333;z-index:1}pre{white-space:pre-wrap;background:#1b1b1b;padding:8px}</style>
<div id="bar"><button id="go">Copy reject commands</button> Tick what sounds wrong, say why, copy, paste to the agent. <pre id="out"></pre></div>${rows}
<script>document.getElementById("go").onclick=()=>{const l=[...document.querySelectorAll(".row")].filter(r=>r.querySelector(".rej").checked).map(r=>"node tools/sfx-request.mjs reject --project ${project} --file "+r.dataset.file+' --note "'+r.querySelector(".note").value.replace(/"/g,"'")+'"');const t=l.join("\\n")||"(nothing ticked)";document.getElementById("out").textContent=t;navigator.clipboard?.writeText(t)}</script>`;
  const f = path.join(audioAuth, "board.html");
  fs.writeFileSync(f, html);
  console.log(`wrote ${f} (${jobs.length} files) — open it in a browser`);
}

// ---------------------------------------------------------------------------------------------- commands
async function main() {
  if (cmd === "status") {
    const jobs = allJobs(opt("category"));
    const record = readJson(recordFile, {});
    const counts = {};
    const todo = [];
    for (const j of jobs) {
      const st = stateOf(j, record);
      counts[st] = (counts[st] ?? 0) + 1;
      if (st !== "ok") todo.push(`${st.padEnd(8)} ${j.file}${record[j.file]?.note ? `  — ${record[j.file].note}` : ""}`);
    }
    if (!flag("next")) for (const l of todo) console.log(l);
    console.log(Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(" · ") || "no catalog entries");
    if (flag("next") && todo.length) console.log(`next: node tools/sfx-request.mjs gen --project ${project}${opt("category") ? ` --category ${opt("category")}` : ""}`);
    return;
  }
  if (cmd === "gen") {
    const record = readJson(recordFile, {});
    let jobs = allJobs(opt("category"));
    const only = opt("only");
    if (only) jobs = jobs.filter((j) => globMatch(only, j.file) || globMatch(only, j.id));
    if (!flag("force")) jobs = jobs.filter((j) => stateOf(j, record) !== "ok");
    process.exitCode = await runJobs(jobs, { concurrency: Number(opt("concurrency", 2)), dry: flag("dry") });
    return;
  }
  if (cmd === "one") {
    const id = opt("id"), prompt = opt("prompt"), category = opt("category");
    if (!id || !prompt || !category) usage();
    const entry = { id, prompt, category, variants: Number(opt("variants", 1)) };
    if (opt("duration")) entry.duration = Number(opt("duration"));
    const jobs = expand(template(), { file: "(one)", category }, entry).map((j) => ({ ...j, catalog: "(one)" }));
    process.exitCode = await runJobs(jobs, { concurrency: 2, dry: flag("dry") });
    return;
  }
  if (cmd === "refit") {
    // re-run post-processing (trim, highpass, level guards) on installed files: no API calls, hash kept
    let jobs = allJobs(opt("category"));
    const only = opt("only");
    if (only) jobs = jobs.filter((j) => globMatch(only, j.file) || globMatch(only, j.id));
    jobs = jobs.filter((j) => fs.existsSync(path.join(assetsAudio, j.file)));
    fs.mkdirSync(stageDir, { recursive: true });
    for (const job of jobs) {
      const dest = path.join(assetsAudio, job.file);
      const raw = path.join(stageDir, `refit.${process.pid}${path.extname(job.file)}`);
      fs.copyFileSync(dest, raw);
      const stats = postProcess(raw, dest, { ...job.post, trim: false, fadeOut: 0 });
      fs.rmSync(raw, { force: true });
      updateRecord((r) => { if (r[job.file]) Object.assign(r[job.file], stats); });
      console.log(`refit ${job.file}  gain ${stats.gain} → ${stats.lufs} LUFS mean ${stats.mean} low ${stats.lowShare}`);
    }
    return;
  }
  if (cmd === "board") return board();
  if (cmd === "reject") {
    const file = opt("file");
    if (!file || !readJson(recordFile, {})[file]) { console.error(`no generated record for ${file}`); process.exit(1); }
    updateRecord((record) => {
      record[file].rejected = true;
      if (opt("note")) record[file].note = opt("note");
    });
    console.log(`${file} marked REJECTED — revise its catalog prompt (the note says why), then gen`);
    return;
  }
  usage();
}
main().catch((e) => { console.error(e.message); process.exit(1); });
