export {
  polyMeshSourceSchema,
  polyFaceSchema,
  faceUvSchema,
  polyGeneratorSchema,
  normalizePolyMesh,
  edgeKey,
  edgeId,
  edgeIdOf,
  emptySelection,
  UV_ANCHORS,
  UV_FILLS,
  type PolyMesh,
  type PolyMeshSource,
  type PolyFace,
  type FaceUv,
  type PolyGenerator,
  type EdgeKey,
  type ElementSelection,
  type UvAnchor,
  type UvFill,
} from "./types.js";
export {
  compilePolyMesh,
  polyMeshCollision,
  triangulateFace,
  computeFaceUvs,
  applyUvSettings,
  planarProject,
  faceUvSettings,
  type CompiledMesh,
  type CompileOptions,
} from "./compile.js";
export {
  buildTopology,
  facePoints,
  faceNormal,
  faceCenter,
  faceEdges,
  faceHasDirectedEdge,
  vertexNormal,
  boundaryEdges,
  isBoundaryEdge,
  boundaryLoops,
  faceRingAround,
  edgeLoop,
  edgeRing,
  growFaces,
  shrinkFaces,
  connectedFaces,
  coplanarFaces,
  facesVertices,
  facesEdges,
  perimeterEdges,
  edgesFaces,
  edgeDirection,
  edgeOutwardInFace,
  type Topology,
} from "./topology.js";
export {
  cloneMesh,
  cloneFace,
  compactMesh,
  transformVertices,
  translateVertices,
  matrixTransformVertices,
  bakeTransform,
  setPivot,
  centerPivot,
  bounds as polyMeshBounds,
  mirror,
  extrudeFaces,
  extrudeEdges,
  insetFaces,
  bevelEdges,
  subdivideFaces,
  subdivideEdges,
  connectEdges,
  connectVertices,
  insertEdgeLoop,
  deleteFaces,
  deleteVertices,
  deleteEdges,
  collapseVertices,
  weldVertices,
  splitVertices,
  detachFaces,
  extractFaces,
  duplicateFaces,
  flipFaces,
  conformNormals,
  mergeFaces,
  triangulateFaces,
  bridgeEdges,
  fillHoles,
  flipEdge,
  setFaceMaterial,
  setSmoothingGroup,
  setFaceColor,
  nextSmoothingGroup,
  ensureMaterialSlot,
  selectionVertices,
  selectionCentroid,
  selectionNormal,
  sanitizeSelection,
  validatePolyMesh,
  type OpResult,
  type ExtrudeMethod,
} from "./ops.js";
export {
  setAutoUv,
  resetUvs,
  freezeUvs,
  planarProjectFaces,
  boxProjectFaces,
  transformUvs,
  fitUvs,
  flipUvs,
  setUvGroup,
  copyUvs,
  uvBounds,
  currentUvs,
  type UvTransform,
} from "./uv-ops.js";
export {
  SHAPES,
  shapeSpec,
  buildShape,
  regenerate,
  cube,
  plane,
  cylinder,
  cone,
  prism,
  stairs,
  arch,
  torus,
  pipe,
  door,
  sphere,
  icosphere,
  polyFromPrimitive,
  polyFromPolygon,
  polyFromFootprint,
  type ShapeParams,
  type ShapeParamSpec,
  type ShapeSpec,
  type PrimitiveSource,
  type PolygonSource,
} from "./shapes.js";
export { setVertexColor } from "./ops.js";
export {
  polyFromGeometry,
  mergeCoplanarPatches,
  inferSmoothing,
  hasValidFaces,
  type FromGeometryOptions,
} from "./from-geometry.js";
export {
  weatherFaces,
  weatheredBoxSource,
  type WeatherOptions,
  type WeatheredBoxOptions,
  type BoxSide,
} from "./weather.js";
export {
  paintGrime,
  type GrimeRule,
  type RadialGrimeRule,
  type HeightBandGrimeRule,
  type FacingGrimeRule,
} from "./tint.js";
