import { z } from "zod";

/**
 * Editable polygon mesh — the engine's ProBuilder-class authoring format.
 *
 * A `mesh.source.kind: "poly"` is a list of shared positions plus a list of
 * n-gon faces indexing into them. It is deliberately the SIMPLEST faithful
 * representation of what a level designer edits: positions are shared
 * (moving a vertex moves every face that uses it), hard vs smooth shading is
 * a per-face smoothing group (ProBuilder's model), materials are per-face
 * submesh slots, and UVs are per-face auto-unwrap settings (or explicit
 * per-corner coordinates once a face has been hand-edited in the UV editor).
 *
 * Everything an editor gizmo or an AI does to the mesh is a pure function in
 * `ops.ts` producing a new PolyMesh, committed as ONE `set-component` op —
 * so mesh editing is undoable, diffable, and file-editable like every other
 * scene mutation. The render-ready triangle buffers are DERIVED (`compile.ts`),
 * never stored: JSON is the authoring truth, not runtime state.
 */

export type Vec3 = [number, number, number];
export type Vec2 = [number, number];

export const UV_ANCHORS = [
  "none",
  "upper-left",
  "upper-center",
  "upper-right",
  "middle-left",
  "middle-center",
  "middle-right",
  "lower-left",
  "lower-center",
  "lower-right",
] as const;
export type UvAnchor = (typeof UV_ANCHORS)[number];

export const UV_FILLS = ["tile", "fit", "stretch"] as const;
export type UvFill = (typeof UV_FILLS)[number];

/**
 * Per-face UV settings. `mode: "auto"` (default) planar-projects the face
 * along its own normal (tangent chosen from the dominant world axis, so a
 * wall's texture stays upright) and then applies the tiling knobs — exactly
 * ProBuilder's AutoUnwrapSettings. `mode: "manual"` freezes explicit
 * per-corner coordinates (`coords`, one per entry in the face's `v`) — what
 * the UV editor writes once a face has been moved/rotated/scaled by hand.
 */
export const faceUvSchema = z.object({
  mode: z.enum(["auto", "manual"]).default("auto"),
  /** Tiling multiplier; 2 = the texture repeats twice across one unit. */
  scale: z.tuple([z.number(), z.number()]).default([1, 1]),
  offset: z.tuple([z.number(), z.number()]).default([0, 0]),
  /** Degrees, counter-clockwise. */
  rotation: z.number().default(0),
  flipU: z.boolean().default(false),
  flipV: z.boolean().default(false),
  swapUV: z.boolean().default(false),
  /** Project in world space so a texture flows across separate objects. */
  worldSpace: z.boolean().default(false),
  /**
   * Where the face's UV bounding box is pinned before offset: "lower-left"
   * puts the texture's origin at the face's lower-left corner (ProBuilder's
   * default — every face starts its tile at its own corner); "none" keeps the
   * raw projection (seamless across coplanar neighbors).
   */
  anchor: z.enum(UV_ANCHORS).default("lower-left"),
  /** tile = keep world scale; fit = squeeze the face's UVs into 0..1 keeping aspect; stretch = fill 0..1 exactly. */
  fill: z.enum(UV_FILLS).default("tile"),
  /**
   * Texture group: faces sharing a nonzero group are projected together on
   * one plane (the group's average normal) so a texture flows across them
   * without a seam. 0 = ungrouped.
   */
  group: z.number().int().min(0).default(0),
  /** manual mode only: one [u, v] per face corner, same order as the face's `v`. */
  coords: z.array(z.tuple([z.number(), z.number()])).optional(),
});
export type FaceUv = z.infer<typeof faceUvSchema>;

export const polyFaceSchema = z.object({
  /** Vertex indices into `vertices`, counter-clockwise seen from outside (right-hand normal). 3+ = triangle/quad/n-gon; n-gons should be planar. */
  v: z.array(z.number().int().min(0)).min(3),
  /** Material slot (index into `materials`); slot 0 falls back to the mesh component's `material`. */
  mat: z.number().int().min(0).default(0),
  /** Smoothing group: 0 = hard-edged (flat shaded); faces sharing a nonzero group share smoothed vertex normals across their common edges. */
  smooth: z.number().int().min(0).default(0),
  uv: faceUvSchema.optional(),
  /** Face tint (vertex color) as #rrggbb; omitted = white/untinted. Materials must opt in to vertex colors to show it. */
  color: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .optional(),
  /** Per-corner tints (one per entry in `v`, same order) — painted vertex colors; win over `color` where present. */
  colors: z
    .array(z.string().regex(/^#[0-9a-fA-F]{6}$/))
    .optional(),
});
export type PolyFace = z.infer<typeof polyFaceSchema>;

/** Parametric origin of a mesh generated by a shape tool — kept until the mesh is edited by hand, so the shape's size/segments can still be tweaked. */
export const polyGeneratorSchema = z.object({
  shape: z.string().min(1),
  params: z.record(z.string(), z.union([z.number(), z.boolean(), z.string()])),
});
export type PolyGenerator = z.infer<typeof polyGeneratorSchema>;

export const polyMeshSourceSchema = z.object({
  kind: z.literal("poly"),
  vertices: z.array(z.tuple([z.number(), z.number(), z.number()])).min(3),
  faces: z.array(polyFaceSchema).min(1),
  /** Material asset GUIDs per submesh slot; a missing/empty slot 0 falls back to the mesh component's `material`. */
  materials: z.array(z.string()).default([]),
  generator: polyGeneratorSchema.optional(),
});
export type PolyMeshSource = z.infer<typeof polyMeshSourceSchema>;

/** The parsed/normalized in-memory form every op takes and returns. Structurally identical to the source; the alias just names the intent. */
export type PolyMesh = PolyMeshSource;

/** An undirected edge as an ordered pair `[min, max]`. */
export type EdgeKey = [number, number];

/** Element selection — what vertex/edge/face tools operate on. */
export interface ElementSelection {
  vertices: number[];
  edges: EdgeKey[];
  faces: number[];
}

export const emptySelection = (): ElementSelection => ({ vertices: [], edges: [], faces: [] });

export function edgeKey(a: number, b: number): EdgeKey {
  return a < b ? [a, b] : [b, a];
}

export function edgeId(a: number, b: number): string {
  return a < b ? `${a}-${b}` : `${b}-${a}`;
}

export function edgeIdOf(edge: EdgeKey): string {
  return edgeId(edge[0], edge[1]);
}

/** Fill schema defaults so ops can rely on every field being present. */
export function normalizePolyMesh(source: unknown): PolyMesh {
  return polyMeshSourceSchema.parse(source);
}
