import { z } from './engine.mjs';
import { reviewSchema } from './schema.mjs';

const point=z.tuple([z.number().finite(),z.number().finite(),z.number().finite()]);
export const poiRequestSchema=z.object({
  version:z.literal(1),
  name:z.string().min(1),
  tier:z.enum(['pinpoint','small','medium','large']).describe('Pinpoint: cache/camp/Seven Whispers. Small: grove. Medium: twice small usable area. Large: twice medium usable area. Dungeon presence is independent.'),
  smallReference:z.object({name:z.string().min(1),usableAreaM2:z.number().positive()}).strict().optional().describe('One explicitly chosen small-grove reference, shared by all area multipliers. Required except for pinpoint. Deferred expansions must not be counted as built.'),
  pinpointAreaM2:z.number().positive().optional().describe('Optional compact discovery footprint. Pinpoints have no grove-size quota.'),
  site:z.object({anchor:point,bounds:z.object({min:point,max:point}).strict(),approachOrigin:point,originDescription:z.string().min(1),zone:z.string().min(1)}).strict().describe('Proposed survey envelope and established playable approach origin. Bounds must include both, air above terrain, and the whole intended route.'),
  intent:z.object({purpose:z.string().min(1),discovery:z.string().min(1),storySources:z.array(z.string().min(1)).default([]),pacing:z.string().min(1)}).strict().describe('Tie the site to terrain and nearby dialogue/quests; explain discovery and zone spacing before building.'),
  dungeon:z.object({mode:z.enum(['none','entrance','instance']),destination:z.string().min(1).optional(),spatialLogic:z.string().min(1).optional()}).strict().default({mode:'none'}).describe('Entrance is a proposed physical entrance; instance also needs an actual transfer destination and end-to-end test. Neither is installed by the planner.'),
  features:z.object({terrain:z.boolean().default(false),grove:z.boolean().default(false),groundedWebs:z.boolean().default(false),building:z.boolean().default(false),statue:z.boolean().default(false)}).strict().default({terrain:false,grove:false,groundedWebs:false,building:false,statue:false}),
  neighbours:z.array(z.object({id:z.string().min(1),position:point,minDistance:z.number().nonnegative()}).strict()).default([]).describe('Site-specific protected spacing from the surrounding survey. No universal dungeon-distance quota.'),
}).strict().superRefine((r,c)=>{
  if(r.tier!=='pinpoint'&&!r.smallReference)c.addIssue({code:'custom',message:'Choose the small usable-area reference before sizing this POI.'});
  const b=r.site.bounds;
  if(!b.min.every((v,i)=>v<b.max[i]))c.addIssue({code:'custom',message:'Survey bounds must have positive extent.'});
  for(const p of [r.site.anchor,r.site.approachOrigin])if(!p.every((v,i)=>v>=b.min[i]&&v<=b.max[i]))c.addIssue({code:'custom',message:'Survey bounds must include the anchor and established approach origin.'});
  if(r.dungeon.mode!=='none'&&!r.dungeon.spatialLogic)c.addIssue({code:'custom',message:'Dungeon entrances require a plausible volume beyond the entrance and route section.'});
  if(r.dungeon.mode==='instance'&&!r.dungeon.destination)c.addIssue({code:'custom',message:'An instance proposal requires a named destination.'});
});

export function planPoi(input){
  const request=poiRequestSchema.parse(input),f=request.features,dungeon=request.dungeon.mode!=='none';
  const multiplier={small:1,medium:2,large:4}[request.tier]??null;
  const target=multiplier===null?(request.pinpointAreaM2??null):request.smallReference.usableAreaM2*multiplier;
  const stages=[
    {id:'survey',role:'site author',action:'Read live context/pins, nearby dialogue and quests, rendered terrain, current assets and nearby destinations. Survey from established playable ground before fixing the layout.',evidence:['Terrain survey and map','Neighbour/road protection notes','Story and discovery rationale']},
    {id:'layout',role:'site author',action:'Reserve connected encounter pockets and retreat routes. Draw the measured plan and section, with area separate from edit footprint. Fit the story to the site; size is not a dungeon quota.',evidence:['Measured plan/section','Usable-area target and measurement method','Approach, exits, camera clearance and encounter capacity assumptions']},
  ];
  if(f.building)stages.push({id:'building',role:'building constructor',action:'Use existing WFC asset modules. Supply footprint, entry/floor levels, front direction, material system and interior connections; return generated building plus geometry/visual checks.',guide:'../MMO/WFC/wfc/README.md',evidence:['Builder request and generated asset manifest','Building geometry/visual review']});
  if(f.statue)stages.push({id:'statue',role:'statue constructor',action:'Bake a static mob/human pose using the statue tool; preserve outfit/gender choices, smooth stone shading and a supported decorated base.',guide:'tools/statue-maker/SKILL.md',evidence:['Statue recipe and outputs','Base/support review']});
  if(dungeon)stages.push({id:'dungeon',role:'dungeon constructor',action:'Follow the dungeon kit workflow with plan/section/concept references, measured entry, plausible buried volume, ramps/levels and final portal destination. Integrate with the outdoor approach.',guide:'docs/blender-dc-authoring.md; current project dungeon-kit README and plan',evidence:['Dungeon construction plan and section','Geometry and traversal reports',...(request.dungeon.mode==='instance'?['Actual instance transfer and return test']:[])]});
  stages.push({id:'catalog',role:'asset author',action:'Before live installation, follow docs/prop-cataloging.md for every new or modified reusable prop, vegetation variant and effect-bearing prefab. Update the owning catalog and project catalog index; preserve source, parts/UVs, materials, dimensions, collision/LOD and attached behavior. Run catalog-check.mjs for all changed runtime outputs, plus the owning importer and visual/performance checks.',guide:'docs/prop-cataloging.md',evidence:['Registered catalog entries and linked intake metadata','Passing catalog coverage/dependency report for all changed outputs','Asset review and provisional/approved status']});
  stages.push({id:'build',role:'site author',action:f.terrain?'Apply bounded terrain shaping through recipe ops; smooth image-guided heights, preserve seams/roads, distort organic walls, and keep usable floors. Apply scene assets through scene ops.':'Use existing terrain with only necessary footing edits. Apply recipe/scene ops and retain inverse batches.',evidence:['Replayable authoring recipe/scripts','Scene and world inverse ops','Protected-feature and seam checks']});
  stages.push({id:'dress',role:'site author',action:'Use catalogued assets with matching world texels, physical support and usable player/camera space.'+(f.grove?' Use seeded local scatter with compatible mesh/size variants and a broad outer tree belt; preserve total density, measure perimeter distribution and keep travel openings.':'')+(f.groundedWebs?' Use triangular webs, each with an actual ground vertex and supported cliff/bark tips. Preserve texels in both axes, visible alpha contacts, and low-edge/route clearance.':''),evidence:['Final asset/material manifest','Attachment and texel checks',...(f.grove?['Scatter recipe and perimeter check']:[])]});
  stages.push(
    {id:'measure',role:'site reviewer',action:'Measure connected usable ground with a declared slope limit, excluding approach spur, walls, steep slopes and solid dressing. Recheck scale after dressing.',evidence:['Area, span, slope, exclusions and connected pockets']},
    {id:'traverse',role:'site reviewer',action:'Run the shared reviewer on current terrain triangles and all final relevant colliders. Include approach, reverse exit and lateral lanes; add enclosure, support and burial probes where applicable. Reject stale report hashes.',evidence:['Final review plan and current model/world bundle','Passing review.json with hashes']},
    {id:'live-review',role:'independent reviewer when available',action:'Walk the actual player controller with procedural vegetation active. Inspect entry, interior, side/section, support contacts and third-person camera; large sites also need distant silhouette views. Numeric success is not visual approval.',evidence:['Real-input walk and camera report','Screenshots and reasoned visual verdict','Remaining limitations']},
    {id:'handoff',role:'site author',action:'Verify installed scene/world match reviewed content. Save replay/undo and evidence paths. State actual mobs/quests/loot/portal behavior and what remains unimplemented; do not claim a visual portal is a working instance.',evidence:['Installation record and current asset identities','Navigation coordinates','Completed checks and honest gameplay status']},
  );
  const reviewPlan=reviewSchema.parse({version:1,name:request.name,kind:!f.building&&!f.statue&&!dungeon?'terrain-route':'site',bounds:request.site.bounds,anchor:request.site.anchor,neighbours:request.neighbours,models:[],routes:[],probes:[],materials:[],intent:{purpose:request.intent.purpose,arrival:request.intent.discovery,interior:dungeon?request.dungeon.spatialLogic:'Outdoor POI; no dungeon transfer proposed.',landscape:f.terrain?'Bounded terrain shaping proposed; survey and final integration required.':'Prefer natural ground and minimal footing edits.'}});
  return {version:1,status:'planned-not-built',scope:'Read-only work plan and incomplete survey template. No terrain, scene, quest or portal changes; no acceptance implied.',request,sizing:{tier:request.tier,smallReference:request.smallReference??null,areaMultiplier:multiplier,targetUsableAreaM2:target,linearMultiplier:multiplier===null?null:Math.sqrt(multiplier),unit:'m² of connected usable ground; not terrain edit bounds'},stages,reviewPlan,rules:'tools/poi-review/poi-design-rules.md',workflowGuide:'tools/poi-review/README.md'};
}
