import * as THREE from 'three/webgpu';
import {createVolume,getVolume,registerVolume,blendVolumePaint,volumePaintSchema,volumeDocSchema,type SceneDoc,type VolumeDoc,type VolumePaint} from '@hitreg/core';
import {SPLAT_ATTRIBUTES} from '@hitreg/render';

/** Paint-only editor: the native volume remains the authoring source; geometry is untouched. */
export function mountVolumePaint(opts:{canvas:HTMLCanvasElement;camera:THREE.PerspectiveCamera;doc:()=>SceneDoc;objects:()=>Map<string,THREE.Object3D>;editing:()=>boolean}){
 const panel=document.createElement('details');panel.style.cssText='position:fixed;right:370px;top:48px;z-index:40;background:#15232aee;color:#e1ddd0;padding:9px;border:1px solid #59646a;font:12px sans-serif;width:210px';panel.innerHTML='<summary>Volume paint</summary><p>Shift-drag on the cave to paint.</p><label>Texture <select aria-label="Volume paint texture"></select></label><p><label>Radius <input aria-label="Volume paint radius" type="number" min="0.25" max="30" step="0.25" value="3" style="width:60px"></label></p><p><label>Strength <input aria-label="Volume paint strength" type="range" min="0.05" max="1" step="0.05" value="0.5"></label></p><p><label>Mode <select aria-label="Volume paint mode"><option value="brush">Brush</option><option value="fill">Angle fill</option></select></label></p><p><label>Angle <input aria-label="Volume fill angle" type="number" min="0" max="180" value="35" style="width:60px"> degrees</label></p><button type="button">Undo paint</button> <button type="button">Redo paint</button><p><button type="button">Save paint</button></p><output>Choose a CSG scene.</output>';document.body.append(panel);
 const mode=panel.querySelectorAll('select')[1]!;const select=panel.querySelector('select')!,inputs=panel.querySelectorAll('input'),buttons=panel.querySelectorAll('button'),status=panel.querySelector('output')!;
 type Session={doc:VolumeDoc;undo:VolumePaint[][];redo:VolumePaint[][];dirty:boolean;baseline:string};const sessions=new Map<string,Session>();let activeId='',root:THREE.Object3D|undefined,session:Session|undefined,lastRoot:THREE.Object3D|undefined;let surfaces:{g:THREE.BufferGeometry;base:Float32Array;weights:Float32Array;count:number}[]=[];
 const ray=new THREE.Raycaster();let dragging=false,lastPoint:THREE.Vector3|undefined;
 function refresh(){if(!opts.editing()){panel.hidden=true;return;}const entry=Object.entries(opts.doc().entities).find(([,e])=>(e.components.mesh as any)?.source?.kind==='csg');panel.hidden=!entry;if(!entry){session=undefined;root=undefined;return;}if(!panel.open)return;const id=(entry[1].components.mesh as any).source.volume as string;const object=opts.objects().get(entry[0]);if(!object)return;if(activeId===id&&lastRoot===object)return;activeId=id;root=object;lastRoot=object;const volume=getVolume(id);if(!volume)return;session=sessions.get(id);if(!session){session={doc:structuredClone(volume.doc),undo:[],redo:[],dirty:false,baseline:JSON.stringify(volume.doc.paint)};sessions.set(id,session);}select.replaceChildren(...session.doc.palette.map((name,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=name;return o;}));surfaces=[];const baseVolume=createVolume({...session.doc,paint:[]});object.traverse(o=>{const m=o as THREE.Mesh;if(!m.isMesh)return;const g=m.geometry,p=g.getAttribute('position'),n=g.getAttribute('normal');if(!p||!n||!g.getAttribute(SPLAT_ATTRIBUTES[0]!))return;const count=session!.doc.palette.length,base=new Float32Array(p.count*count),scratch=new Float32Array(count+3);for(let i=0;i<p.count;i++){baseVolume.surfaceAt(p.getX(i),p.getY(i),p.getZ(i),n.getY(i),scratch,0);base.set(scratch.subarray(0,count),i*count);}surfaces.push({g,base,weights:base.slice(),count});});repaint();status.textContent=session.dirty?'Unsaved paint':'Paint ready';}
 function upload(s:typeof surfaces[number]){for(let j=0;j<Math.ceil(s.count/4);j++){const a=s.g.getAttribute(SPLAT_ATTRIBUTES[j]!);if(!a)continue;for(let i=0;i<a.count;i++)for(let k=0;k<4;k++)a.setComponent(i,k,j*4+k<s.count?s.weights[i*s.count+j*4+k]!:0);a.needsUpdate=true;}}
 function apply(stroke:VolumePaint,flush=true){for(const s of surfaces){const p=s.g.getAttribute('position');for(let i=0;i<p.count;i++)blendVolumePaint(stroke,p.getX(i),p.getY(i),p.getZ(i),s.weights,i*s.count,s.count,[s.g.getAttribute('normal').getX(i),s.g.getAttribute('normal').getY(i),s.g.getAttribute('normal').getZ(i)]);if(flush)upload(s);}}
 function repaint(){for(const s of surfaces)s.weights.set(s.base);for(const stroke of session?.doc.paint??[])apply(stroke,false);for(const s of surfaces)upload(s);}
 function stroke(e:PointerEvent){if(!session||!root)return;const radius=Number(inputs[0]!.value),strength=Number(inputs[1]!.value);if(!Number.isFinite(radius)||radius<=0||radius>30)return;const r=opts.canvas.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),opts.camera);const hit=ray.intersectObject(root,true)[0];if(!hit)return;const p=root.worldToLocal(hit.point.clone());if(lastPoint&&p.distanceTo(lastPoint)<radius*.2)return;const parsedPaint=volumePaintSchema.safeParse({id:crypto.randomUUID(),center:p.toArray(),radius,strength,layer:Number(select.value),fill:mode.value==='fill',maxAngle:mode.value==='fill'?Number(inputs[2]!.value):180,...(mode.value==='fill'&&hit.face?{normal:hit.face.normal.toArray()}: {})});if(!parsedPaint.success){status.textContent='Check radius, strength and angle';return;}const paint=parsedPaint.data;if(!dragging){session.undo.push(structuredClone(session.doc.paint));session.redo=[];dragging=true;}lastPoint=p;session.doc.paint.push(paint);session.dirty=true;apply(paint);status.textContent='Unsaved paint · '+session.doc.paint.length+' dabs';}
 const down=(e:PointerEvent)=>{if(e.button!==0||!e.shiftKey||!panel.open||panel.hidden)return;e.preventDefault();e.stopImmediatePropagation();lastPoint=undefined;stroke(e);};const move=(e:PointerEvent)=>{if(!dragging)return;e.preventDefault();e.stopImmediatePropagation();if(mode.value!=='fill')stroke(e);};const up=()=>{dragging=false;lastPoint=undefined;};opts.canvas.addEventListener('pointerdown',down,true);opts.canvas.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);
 buttons[0]!.onclick=()=>{if(!session||!session.undo.length)return;session.redo.push(structuredClone(session.doc.paint));session.doc.paint=session.undo.pop()!;session.dirty=true;repaint();status.textContent='Undone · unsaved';};buttons[1]!.onclick=()=>{if(!session||!session.redo.length)return;session.undo.push(structuredClone(session.doc.paint));session.doc.paint=session.redo.pop()!;session.dirty=true;repaint();status.textContent='Redone · unsaved';};
 buttons[2]!.onclick=async()=>{if(!session)return;const target=session,id=activeId,snapshot=volumeDocSchema.parse(target.doc);status.textContent='Saving…';try{const read=await fetch('/__hitreg/asset-file?file='+encodeURIComponent('volumes/'+id+'.json'));if(!read.ok)throw Error('Could not read the current volume');const fresh=volumeDocSchema.parse(await read.json());if(JSON.stringify(fresh.paint)!==target.baseline)throw Error('Paint changed on disk. Reload before saving to avoid overwriting it.');const content=volumeDocSchema.parse({...fresh,paint:snapshot.paint});const res=await fetch('/__hitreg/write-asset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({file:'volumes/'+id+'.json',content:JSON.stringify(content,null,2)})});if(!res.ok)throw Error('Save failed: '+res.status);registerVolume(id,content);target.baseline=JSON.stringify(snapshot.paint);if(JSON.stringify(target.doc.paint)===JSON.stringify(snapshot.paint))target.dirty=false;status.textContent=target.dirty?'Saved snapshot · newer paint unsaved':'Paint saved';}catch(e){status.textContent=String(e);}};
 const timer=window.setInterval(refresh,700);refresh();return()=>{clearInterval(timer);panel.remove();opts.canvas.removeEventListener('pointerdown',down,true);opts.canvas.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true);};
}

